# Site settings
title: Your Slack archive
email: example@example.com
description: > # this means to ignore newlines until "baseurl:"
  An archive of your community
baseurl: "slack-archive" # the subpath of your site, e.g. /blog/
url: "https://example.com/" # the base hostname & protocol for your site
twitter_username: twitterhandle
github_username: githubhandle

# Build settings
markdown: kramdown

exclude:
  - archives/
  - preproc
