name: Deploy to pages
on:
  push:
    branches:
      - main

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Racket
        uses: Bogdanp/setup-racket@v0.11
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: '8.0'

      - name: Install viewer
        run: raco pkg install --deps search-auto --no-docs slack-archive-viewer

      - name: Build
        run: racket -l slack-archive-viewer archives

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
