name: Deploy to pages
on:
  push:
    branches:
      - main

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Extract Archives
        run: |
          mkdir _data
          cd _data
          for archive in ../archives/*.zip ; do unzip -o "$archive" ; done

      - name: Pre-process archives
        run: ./preproc _data $(nproc)

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Build
        run: |
          gem install jekyll
          jekyll build --trace

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
